modLoader="javafml" #mandatory

loaderVersion="[40,)" #mandatory
license="All rights reserved"

[[mods]]
modId = "createarsenal" #mandatory
version = "0.1" #mandatory
displayName = "Create Arsenal" #mandatory
logoFile = "createarsenal.png" #optional
credits = "The mod is made by Create Arsenal team. Big thanks to the Create team for making the parent mod." #optional
authors = "CeoOfGoogle, amik, Truffle" #optional
# The description text for the mod (multi line!) (#mandatory)
description = '''
Create: Arsenal is an addon for the Create mod for Minecraft. We add a wide variety of stationary weapons, made to work perfectly together with
Create: Aeronautics and its addons, but also the Clockwork mod and another addon called Create: Kaboom which adds many explosives
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.

[[dependencies.createarsenal]]
modId = "forge"
mandatory = true
versionRange = "[43.2.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.createarsenal]]
modId = "minecraft"
mandatory = true
versionRange = "1.19.2"
ordering = "NONE"
side = "BOTH"

[[dependencies.createarsenal]]
modId = "create"
mandatory = true
versionRange = "0.5.1.e-44"
ordering = "NONE"
side = "BOTH"
